# GET http://localhost:3000/api/persons

# GET http://localhost:3000/info


# DELETE http://localhost:3001/api/persons/2

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "id": 3,
    "name": "Arto",
    "number": "040-123456"
 
}


